pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: Docker@0
  displayName: 'Run Pandoc Container'
  inputs:
    action: 'Run an image'
    imageName: seesharprun/content-generation-pandoc:0.1.0
    containerCommand: 'pandoc -v'
    detached: false